### ISSUE TITLE
Using bindlib as a library fails with oasis/ocamlbuild

### ISSUE THREAD

**Issue by francoisthire** [rlepigre/ocaml-bindlib#2]
One can try to create the following small project:

_oasis file:
```text
OASISFormat: 0.4
Name: test
Version: 0.1
Synopsis: test
Authors: François Thiré <franth2@gmail.com>
License: GPL

BuildTools: ocamlbuild
Plugins: META (0.4), DevFiles (0.4)

Executable "test"
  Path: src
  MainIs: test.ml
  CompiledObject: native
  BuildDepends: bindlib
```

src/test.ml:
```ocaml
let _ = Printf.printf "success\n"
```

then launch
```bash
oasis setup
make
```

it fails with the following message:

```text
ocaml setup.ml -build 
Finished, 1 target (0 cached) in 00:00:00.
+ /home/fthire/.opam/4.04.2/bin/ocamlfind ocamlopt -g -linkpkg -package bindlib -I src src/test.cmx -o src/test.native
File "_none_", line 1:
Error: The file /home/fthire/.opam/4.04.2/lib/bindlib/bindlib.cmxa is not a compilation unit description
Command exited with code 2.
Compilation unsuccessful after building 4 targets (0 cached) in 00:00:00.
E: Failure("Command ''/home/fthire/.opam/4.04.2/bin/ocamlbuild' src/test.native -tag debug' terminated with error code 10")
Makefile:7: recipe for target 'build' failed
make: *** [build] Error 1
```

Moreover, using only ocamlbuild the compilation still fails  (even after removing the files generated by _oasis):

```bash
ocamlbuild -package bindlib src/test.native
```

I forked bindlib from github and then I did

```bash
make
make install
```

So I don't know where the problem comes from. There is a few links about that kind of error. I found [this](http://caml-list.inria.narkive.com/3om3n5rI/not-a-compilation-unit-description) but it was not very helpful. I hope that it is possible to reproduce the bug.

**Comment by francoisthire** [comment]
I have tried to do a
```
make clean
make
make install
```

and it seems to work now but I have no idea why.

**Comment by rlepigre** [comment]
Well, that's really weird... It was probably a local thing then, right? Maybe your build was in a bad state, with remaining files from previous attempts and a changed configuration.
