### ISSUE TITLE
more tests

### ISSUE THREAD

**Issue by craff** [rlepigre/ocaml-bindlib#27]
dune runtest should run all examples and check output. The following are missing:
- [ ] more_lambda
- [x] metavar (but build a dependency on pacomb) ?

**Comment by craff** [comment]
I will submit a PR when #26 is resolved in one way or another, and when we decide for pacomb dependency.

**Comment by craff** [comment]
PR #26 now contains a test for metavar. 
However, more_lambda does not product any output. May be we should test the functions it provides ?

**Comment by rlepigre** [comment]
Let's close this, since this is mostly fixed.
