### ISSUE TITLE
Hashing terms with binders?

### ISSUE THREAD

**Issue by qcfu-bu** [rlepigre/ocaml-bindlib#33]
Suppose I have a simple language with binders, stlc for instance.

```
type ty =
  | Unit
  | Tuple of ty * ty
  | Arrow of ty * ty

type tm =
  | It
  | Var of tm var
  | Lam of ty * (tm, tm) binder
  | App of tm * tm
  | Pair of tm * tm
  | ProjL of tm
  | ProjR of tm
```

Is it possible to create a hash function for `tm`? Unbinding a `(tm, tm) binder` will produce a fresh variable which means that alpha-equivalent terms may not have the same hash values.

I know this is possible for encodings such as locally-nameless  because you can just go under the binder without actually unbinding it. I believe this is what the [Coq kernel code](https://github.com/coq/coq/blob/9f2d0734338da7db55b4438c1985b10a3abfc17f/kernel/constr.ml#LL1326C11-L1326C11) does.

**Comment by rlepigre** [comment]
This is definitely possible, as you can easily convert from your representation of terms to any other representation (full de Bruijn indices, locally nameless, ...), however doing it in this way would be pretty inefficient.

One possible approach (possibly the most efficient) is to extend your type of terms with a special node for "variable hashes". So, in your case that would be something like:
```ocaml
type tm =
  | It
  | Var of tm var
  | Lam of ty * (tm, tm) binder
  | App of tm * tm
  | Pair of tm * tm
  | ProjL of tm
  | ProjR of tm
  | VHash of int (* Only used for hashing bound variables. *)
```
And then you can implement your hashing function like this:
```ocaml
let hash : tm -> int = fun t ->
  let next : unit -> int =
    let counter = ref (-1) in
    fun _ -> incr counter; VHash(!counter)
  in
  let rec hash t =
    match t with
    | It        -> Hashtbl.hash (`It)
    | Var(x)    -> Hashtbl.hash (`Var  , Bindlib.hash_var x) (* Free var. *)
    | Lam(_,b)  -> Hashtbl.hash (`Lam  , hash (Bindlib.subst b (next ())))
    | App(t,u)  -> Hashtbl.hash (`App  , hash t, hash u)
    | Pair(t,u) -> Hashtbl.hash (`Pair , hash t, hash u)
    | ProjL(t)  -> Hashtbl.hash (`ProjL, hash t)
    | ProjR(t)  -> Hashtbl.hash (`ProjR, hash t)
    | VHash(i)  -> i
  in
  hash t
```
We have used something like that before in [PML](https://github.com/rlepigre/pml/blob/master/src/kernel/hash.ml), where we use reserved constructors for a bunch of different things. There is also an (not super clear, nor fully worked out) example in the Bindlib repository for doing [hash-consing](https://github.com/rlepigre/ocaml-bindlib/blob/master/examples/hashcons.ml).

An alternative to having a special constructor is to simply rely on a hash table to store the hash for bound variables. That would give something like the following (I have not tested or compiled any of this code and the above).
```ocaml
let hash : tm -> int =
  let module H = Hashtbl.Make(
    struct
      type t = tm Bindlib.var
      let hash = Bindlib.hash_var
      let equal = Bindlib.eq_vars
    end)
  in
  fun t ->
    let bound = H.create 5 in
    let next : unit -> int =
      let counter = ref (-1) in
      fun _ -> incr counter; VHash(!counter)
    in
    let hash_var x =
       (* Only bound variables have a stored hash. *)
      try H.find x with Not_found -> Bindlib.hash_var x
    in
    let rec hash t =
    | It        -> Hashtbl.hash (`It)
    | Var(x)    -> Hashtbl.hash (`Var, hash_var x)
    | Lam(_,b)  ->
        let (x, t) = Bindlib.unbind b in
        Hashtbl.add bound x (next_hash ());
        Hashtbl.hash (`Lam, hash t)
    | App(t,u)  -> Hashtbl.hash (`App  , hash t, hash u)
    | Pair(t,u) -> Hashtbl.hash (`Pair , hash t, hash u)
    | ProjL(t)  -> Hashtbl.hash (`ProjL, hash t)
    | ProjR(t)  -> Hashtbl.hash (`ProjR, hash t)
    in
    hash t
```

**Comment by qcfu-bu** [comment]
The solution with the extended `VHash` constructor is very nice. Thanks for the help!

**Comment by craff** [comment]
Bonjour,

Il y a un example hashcons.ml disponible avec bindlib. Je ne sais pas
où/si opam installe les examples, mais ils sont sur github.

A+
Christophe

qcfu-bu writes:

> Suppose I have a simple language with binders, stlc for instance.
>
> ```
> type ty =
>   | Unit
>   | Tuple of ty * ty
>   | Arrow of ty * ty
>
> type tm =
>   | It
>   | Var of tm var
>   | Lam of ty * (tm, tm) binder
>   | App of tm * tm
>   | Pair of tm * tm
>   | ProjL of tm
>   | ProjR of tm
> ```
>
> Is it possible to create a hash function for `tm`? Unbinding a `(tm, tm) binder` will produce a fresh variable which means that alpha-equivalent terms may not have the same hash values.
>
> I know this is possible for encodings such as locally-nameless  because you can just go under the binder without actually unbinding it. I believe this is what the [Coq kernel code](https://github.com/coq/coq/blob/9f2d0734338da7db55b4438c1985b10a3abfc17f/kernel/constr.ml#LL1326C11-L1326C11) does.


--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu

Ce mail est signé avec pgp (Pièce jointe signature.asc, clef sur https://raffalli.eu/pgp)
This mail is signed pgp (Attachment signature.asc, clef on https://raffalli.eu/pgp)
